### ISSUE TITLE
make_data.py

### ISSUE THREAD

**Issue by Ramtin92** [Xiaohui9607/mmvp#1]
I think, there is a minor bug in this file. It seems it doesn't capture all the haptic and audios to their corresponding vision files to create npy file; e.g.

**vision ../../data/CY101/vision_data_part2/egg_cardboard/trial_1/exec_4/post_tap_look
vision ../../data/CY101/vision_data_part2/egg_cardboard/trial_1/exec_4/shake
vision ../../data/CY101/vision_data_part2/egg_cardboard/trial_1/exec_4/tap
vision ../../data/CY101/vision_data_part2/egg_cardboard/trial_1/exec_4/low_drop**
vision ../../data/CY101/vision_data_part2/egg_cardboard/trial_1/exec_4/push
haptic ../../data/CY101/rc_data/egg_cardboard/trial_1/exec_4/push/proprioception/ttrq0.txt
audio ../../data/CY101/rc_data/egg_cardboard/trial_1/exec_4/push/hearing/*.wav

For the [1,2,3,4] lines, there is no correspoding npy files which causes that it doesn't generate npy files for the. Is it correct or I'm missing something? Thanks you.

**Comment by Xiaohui9607** [comment]
Do you mean that there is no npy file for behavior tap, shake,
post_tap_look, etc? I just chose three kinds of behavior to generate npy
files, which are push, crush and poke. For the rest of them, for now, we
just ignore them.
